cvs automake has problems with `make distcheck' well - use `make dist' instead.
git-svn-id: file:///home/survex-svn/survex/trunk@497 4b37db11-9a0c-4f06-9ece-9ab7cdaee568

diff --git a/make_release b/make_release
--- a/make_release
+++ b/make_release
@@ -18,8 +18,10 @@ if ! ./configure ; then
    echo configure failed
    exit 1
 fi
-if ! make distcheck ; then
-   echo make distcheck failed
+# make distcheck fails - cvs version of automake doesn't clean up all the
+# files it creates...
+if ! make dist ; then
+   echo make dist failed
    exit 1
 fi
 if ! make dos_doc_zip ; then
