modified to work on my box or mrs30
git-svn-id: file:///home/survex-svn/survex/trunk@2493 4b37db11-9a0c-4f06-9ece-9ab7cdaee568

diff --git a/make_release b/make_release
--- a/make_release
+++ b/make_release
@@ -159,7 +159,23 @@ if expr "$mk" : '.*\<mingw\>'; then
 	 export CXX
       fi
    fi
-   if ! ./configure --host=mingw32 --build="$build_platform" --with-x=no WXCONFIG=/opt/wxmsw-2.4.0/bin/wxmsw-2.4-i686-mingw32-config VLDFLAGS="-s -L/opt/rx-win32/lib" CPPFLAGS=-I/opt/rx-win32/include CAVEROT= CFLAGS=-Werror CXXFLAGS=-Werror ; then
+   for WXCONFIG in /usr/i586-mingw32msvc/bin/wxmsw-2.4-i586-mingw32msvc-config \
+	    /opt/wxmsw-2.4.0/bin/wxmsw-2.4-i686-mingw32-config \
+	    ""
+   do
+      test -f "$WXCONFIG" && break
+   done
+   if test -z "$WXCONFIG" ; then
+      echo "couldn't find wx-config for mingw"
+      exit 1
+   fi
+   LDFLAGS=
+   PASS_CPPFLAGS=
+   if test -d /opt/rx-win32 ; then
+      LDFLAGS=/opt/rx-win32/lib
+      CPPFLAGS=-I/opt/rx-win32/include
+   fi
+   if ! ./configure --host=mingw32 --build="$build_platform" --with-x=no WXCONFIG="$WXCONFIG" LDFLAGS="-s $LDFLAGS-L/opt/rx-win32/lib" CPPFLAGS="$CPPFLAGS" CAVEROT= CFLAGS=-Werror CXXFLAGS=-Werror ; then
       echo mingw configure failed
       exit 1
    fi
